### ISSUE TITLE
v2.0.5升级至v2.0.6报错 javax.crypto.BadPaddingException

### ISSUE THREAD

**Issue by IsSeptember** [TencentBlueKing/ci-checkout#28]
插件配置：
代码库：按仓库URL输入
授权类型：凭证（用户名+密码）

连续构建流水线约50次，拉取代码插件约1次报错，内容如下

![image](https://user-images.githubusercontent.com/54738906/192769588-e0530a09-c009-41a7-909d-10dd4871591b.png)
[java-atom-sdk] delete sdkFile result is:true
git checkout core version: 1.0.18
Start to get the credential(bruceyang)
git checkout error
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during 
decryption.
    at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
    at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
    at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
    at com.sun.crypto.provider.DESCipher.engineDoFinal(DESCipher.java:314)
    at javax.crypto.Cipher.doFinal(Cipher.java:2164)
    at com.tencent.bk.devops.git.core.util.DHUtil.decrypt(DHUtil.kt:93)
    at com.tencent.bk.devops.git.core.service.auth.CredentialGitAuthProvider.decode(CredentialGitAuthProvider.kt:124)
    at com.tencent.bk.devops.git.core.service.auth.CredentialGitAuthProvider.decode(CredentialGitAuthProvider.kt:112)
    at com.tencent.bk.devops.git.core.service.auth.CredentialGitAuthProvider.getCredential(CredentialGitAuthProvider.kt:105
)
    at com.tencent.bk.devops.git.core.service.auth.CredentialGitAuthProvider.getAuthInfo(CredentialGitAuthProvider.kt:52)
    at com.tencent.bk.devops.git.core.service.input.GitCodeCommandAtomParamInputAdapter.getInputs(GitCodeCommandAtomParamIn
putAdapter.kt:103)
    at com.tencent.bk.devops.git.core.service.input.CheckoutAtomParamInputAdapter.byRepositoryUrl(CheckoutAtomParamInputAda
pter.kt:167)
    at com.tencent.bk.devops.git.core.service.input.CheckoutAtomParamInputAdapter.getInputs(CheckoutAtomParamInputAdapter.k
t:48)
    at com.tencent.bk.devops.git.core.GitCheckoutRunner.run(GitCheckoutRunner.kt:83)
    at com.tencent.devops.git.CheckoutAtom.execute(CheckoutAtom.kt:76)
    at com.tencent.bk.devops.atom.AtomRunner.main(AtomRunner.java:31)

**Comment by IsSeptember** [comment]
蓝盾 v1.7.36

**Comment by IsSeptember** [comment]
> 蓝盾对应的哪个版本
v1.7.36

**Comment by IsSeptember** [comment]
> > > 蓝盾对应的哪个版本
> > > v1.7.36
> > > 你是第三方构建机还是公共构建机？

第三方构建机。社区版蓝盾，Linux型私有单构建机

**Comment by mingshewhe** [comment]
> > > > 蓝盾对应的哪个版本
> > > > v1.7.36
> > > > 你是第三方构建机还是公共构建机？
> 
> 第三方构建机。社区版蓝盾，Linux型私有单构建机

这个应该是你的构建机上有一个老的加解密包，服务端升级了加解密工具包，但是构建机没有升级导致偶现失败，升级原因https://github.com/Tencent/bk-ci/issues/5903
可以找到构建机安装目录，先看下路径下是否有jre/lib/ext/bcprov-jdk16-1.46.jar jar包，如果有就删除。插件已经添加了最新的依赖，不依赖构建机上的依赖了

**Comment by IsSeptember** [comment]
> > > > > 蓝盾对应的哪个版本
> > > > > v1.7.36
> > > > > 你是第三方构建机还是公共构建机？
> > 
> > 
> > 第三方构建机。社区版蓝盾，Linux型私有单构建机
> 
> 这个应该是你的构建机上有一个老的加解密包，服务端升级了加解密工具包，但是构建机没有升级导致偶现失败，升级原因[Tencent/bk-ci#5903](https://github.com/Tencent/bk-ci/issues/5903) 可以找到构建机安装目录，先看下路径下是否有jre/lib/ext/bcprov-jdk16-1.46.jar jar包，如果有就删除。插件已经添加了最新的依赖，不依赖构建机上的依赖了

感谢，的确有这个jar包，删除后未出现该错误
